version: '3.4'

services:
  nginx:
    image: nginx:latest
    build:
      context: ../../
      dockerfile: tz-local/docker/nginx/Dockerfile
    volumes:
      - ../../tz-local/docker/nginx/conf/:/etc/nginx/conf.d/:rw
      - ../../tz-local/docker/certbot/www/:/var/www/certbot/:rw
      - ../../:/vagrant/
    ports:
      - 80:80
      - 443:443
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ../../tz-local/docker/certbot/www/:/var/www/certbot/:rw
      - ../../tz-local/docker/certbot/conf/:/etc/letsencrypt/:rw
volumes:
     app-volume:
