version: '3.4'

services:
  nginx:
    image: nginx:latest
    build:
      context: ../../
      dockerfile: tz-local/docker/nginx/Dockerfile
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ../../:/vagrant/
    ports:
      - 80:80
      - 443:443
    restart: always

  certbot:
      image: certbot/certbot:latest
      volumes:
        - ../../wordpress/certbot/www/:/vagrant/wordpress/certbot/:rw
        - ../../wordpress/certbot/conf/:/etc/letsencrypt/:rw
volumes:
     app-volume:
